//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;/html&gt;.
        /// </summary>
        internal static string ParserTests_Images_are_not_extracted_from_html__html___html_ {
            get {
                return ResourceManager.GetString("ParserTests_Images_are_not_extracted_from_html__html___html_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;p&gt;some p&lt;/p&gt;
        ///&lt;img src=&quot;mdn-logo-sm.png&quot; alt=&quot;MDN&quot;&gt;
        ///&lt;br&gt;
        ///&lt;imgsrc=&quot;some-other.jpg&quot; alt&quot;test&quot;&gt;
        ///&lt;a href=&quot;/&quot;&gt;MDN&lt;img src=&quot;mdn-logo-sm.png&quot; alt=&quot;MDN&quot;&gt;&lt;/a&gt;
        ///&lt;div class=&quot;tt&quot;&gt; some text &lt;/div&gt;
        ///&lt;a href=&quot;/&quot;&gt;MDN&lt;img src=&quot;logo2.png&quot; alt=&quot;MDN&quot;&gt;&lt;/a&gt;
        ///&lt;a href=&quot;/&quot;&gt;MDN&lt;img src=&quot;http://www.gooogle.com/logo3.png&quot; alt=&quot;MDN&quot;&gt;&lt;/a&gt;
        ///&lt;a href=&quot;https://www.google.com/&quot; &gt; some link &lt;/a&gt;
        ///&lt;a href=&quot;secondpage&quot; &gt; some link &lt;/a&gt;
        ///&lt;a href=&quot;/thirdpage&quot; &gt; some link &lt;/a&gt;
        ///&lt;a href=&quot;https://localh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testHtmlWith2DifferentImagesAnd4Links {
            get {
                return ResourceManager.GetString("testHtmlWith2DifferentImagesAnd4Links", resourceCulture);
            }
        }
    }
}
